---
name: Deploy to Azure App Services
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v4
      - name: Setup Node 10.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: |
          npm install
      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: nodejs-deploy
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          package: .